### ISSUE TITLE
This directory automatically gets mounted to /etc/sentry

### ISSUE THREAD

**Issue by drmrbrewer** [getsentry/develop#500]
The [restore section](https://develop.sentry.dev/self-hosted/backup/#restore) of the page relating to backups has the following statement:

> This directory automatically gets mounted to /etc/sentry so you can run the following to restore your backup

But in my installation, this directory is *not* mounted to `/etc/sentry`... there is nothing at all mounted to `/etc/sentry`.  So either there's a bug in the docs, or a bug in the installation.

**Comment by drmrbrewer** [comment]
If it means that the directory is mounted to `/etc/sentry` *as part of the import process*, and I just run that restore command as-is (with `backup.json` having been dumped into the `sentry` sub-folder within the main `self-hosted` repo folder `~/sentry/self-hosted`), I just get the following errors:

	~/sentry/self-hosted# docker compose run --rm -T web import /etc/sentry/backup.json
	[+] Running 16/0
	 ⠿ Container sentry-self-hosted-memcached-1                                 Running                                  0.0s
	 ⠿ Container sentry-self-hosted-postgres-1                                  Running                                  0.0s
	 ⠿ Container sentry-self-hosted-zookeeper-1                                 Running                                  0.0s
	 ⠿ Container sentry-self-hosted-clickhouse-1                                Running                                  0.0s
	 ⠿ Container sentry-self-hosted-kafka-1                                     Running                                  0.0s
	 ⠿ Container sentry-self-hosted-symbolicator-1                              Running                                  0.0s
	 ⠿ Container sentry-self-hosted-smtp-1                                      Running                                  0.0s
	 ⠿ Container sentry-self-hosted-redis-1                                     Running                                  0.0s
	 ⠿ Container sentry-self-hosted-snuba-outcomes-consumer-1                   Running                                  0.0s
	 ⠿ Container sentry-self-hosted-snuba-subscription-consumer-transactions-1  Running                                  0.0s
	 ⠿ Container sentry-self-hosted-snuba-sessions-consumer-1                   Running                                  0.0s
	 ⠿ Container sentry-self-hosted-snuba-consumer-1                            Running                                  0.0s
	 ⠿ Container sentry-self-hosted-snuba-replacer-1                            Running                                  0.0s
	 ⠿ Container sentry-self-hosted-snuba-api-1                                 Running                                  0.0s
	 ⠿ Container sentry-self-hosted-snuba-transactions-consumer-1               Running                                  0.0s
	 ⠿ Container sentry-self-hosted-snuba-subscription-consumer-events-1        Running                                  0.0s
	Updating certificates in /etc/ssl/certs...
	0 added, 0 removed; done.
	Running hooks in /etc/ca-certificates/update.d...
	done.
	11:20:16 [INFO] sentry.plugins.github: apps-not-configured
	/usr/local/lib/python3.8/site-packages/sentry/runner/initializer.py:551: DeprecatedSettingWarning: The SENTRY_URL_PREFIX setting is deprecated. Please use SENTRY_OPTIONS['system.url-prefix'] instead.
	  warnings.warn(DeprecatedSettingWarning(old, "SENTRY_OPTIONS['%s']" % new))
	/usr/local/lib/python3.8/site-packages/memcache.py:1303: SyntaxWarning: "is" with a literal. Did you mean "=="?
	  if key is '':
	/usr/local/lib/python3.8/site-packages/memcache.py:1304: SyntaxWarning: "is" with a literal. Did you mean "=="?
	  if key_extra_len is 0:
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.8/site-packages/django/core/serializers/json.py", line 68, in Deserializer
		objects = json.loads(stream_or_string)
	  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
		return _default_decoder.decode(s)
	  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
		obj, end = self.raw_decode(s, idx=_w(s, 0).end())
	  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
		raise JSONDecodeError("Expecting value", s, err.value) from None
	json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

	The above exception was the direct cause of the following exception:

	Traceback (most recent call last):
	  File "/usr/local/bin/sentry", line 8, in <module>
		sys.exit(main())
	  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 188, in main
		func(**kwargs)
	  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
		return self.main(*args, **kwargs)
	  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
		rv = self.invoke(ctx)
	  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
		return _process_result(sub_ctx.command.invoke(sub_ctx))
	  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
		return ctx.invoke(self.callback, **ctx.params)
	  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
		return callback(*args, **kwargs)
	  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
		return f(get_current_context(), *args, **kwargs)
	  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
		return ctx.invoke(f, *args, **kwargs)
	  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
		return callback(*args, **kwargs)
	  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/backup.py", line 19, in import_
		for obj in serializers.deserialize("json", src, stream=True, use_natural_keys=True):
	  File "/usr/local/lib/python3.8/site-packages/django/core/serializers/json.py", line 73, in Deserializer
		raise DeserializationError() from exc
	django.core.serializers.base.DeserializationError
